version: "3.9"
services:
  robots_frontend_container:
    build:
      context: ..
      dockerfile: docker-compose/robots_frontend.Dockerfile
    # image: robots_frontend
    ports:
      - "5000:5000"
    volumes:
      - ../client/robots:/app

  moonbeam_wrapper_container:
    build:
      context: ..
      dockerfile: docker-compose/moonbeam_wrapper.Dockerfile
    # image: moonbeam_wrapper
    ports:
      - "8080:8080"
    volumes:
      - ../server-moonbeam-wrapper/app:/app