version: "3.9"
services:
  robots_frontend_container:
    build:
      context: ..
      dockerfile: mitbtcexpo22-PrometheusBot/robots_frontend.Dockerfile
    ports:
      - "5000:5000"

  moonbeam_wrapper_container:
    build:
      context: ..
      dockerfile: mitbtcexpo22-PrometheusBot/moonbeam_wrapper.Dockerfile
    ports:
      - "8080:8080"